/**
 * Example C Testbench for VCS Flow
 * Simple C-based testbench for processor verification
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define MAX_VECTORS 1000
#define MAX_LINE_LENGTH 256

typedef struct {
    char name[64];
    FILE* log_file;
    int vector_count;
    char vectors[MAX_VECTORS][MAX_LINE_LENGTH];
} testbench_t;

int init_testbench(testbench_t* tb, const char* name) {
    strncpy(tb->name, name, sizeof(tb->name) - 1);
    tb->name[sizeof(tb->name) - 1] = '\0';
    tb->vector_count = 0;
    
    char log_filename[128];
    snprintf(log_filename, sizeof(log_filename), "logs/testbenches/%s_c.log", name);
    
    tb->log_file = fopen(log_filename, "w");
    if (!tb->log_file) {
        printf("Warning: Could not open log file %s\n", log_filename);
    }
    
    return 0;
}

void log_message(testbench_t* tb, const char* message) {
    time_t now = time(NULL);
    char* time_str = ctime(&now);
    time_str[strlen(time_str) - 1] = '\0'; // Remove newline
    
    if (tb->log_file) {
        fprintf(tb->log_file, "[%s] %s\n", time_str, message);
        fflush(tb->log_file);
    }
    
    printf("[%s] %s\n", tb->name, message);
}

void generate_test_vectors(testbench_t* tb) {
    log_message(tb, "Generating test vectors...");
    
    srand(time(NULL));
    
    for (int i = 0; i < 50 && i < MAX_VECTORS; i++) {
        snprintf(tb->vectors[i], MAX_LINE_LENGTH, 
                "test_vector_%d_data_0x%04X", i, rand() & 0xFFFF);
        tb->vector_count++;
    }
    
    char msg[128];
    snprintf(msg, sizeof(msg), "Generated %d test vectors", tb->vector_count);
    log_message(tb, msg);
}

int create_stimulus_files(testbench_t* tb) {
    log_message(tb, "Creating stimulus files for VCS...");
    
    char filename[128];
    snprintf(filename, sizeof(filename), "tb/stimulus_%s.txt", tb->name);
    
    FILE* f = fopen(filename, "w");
    if (!f) {
        log_message(tb, "ERROR: Could not create stimulus file");
        return 1;
    }
    
    fprintf(f, "# Stimulus file for %s\n", tb->name);
    fprintf(f, "# Generated by C testbench\n");
    fprintf(f, "# Vector count: %d\n", tb->vector_count);
    fprintf(f, "\n");
    
    for (int i = 0; i < tb->vector_count; i++) {
        fprintf(f, "%s\n", tb->vectors[i]);
    }
    
    fclose(f);
    
    char msg[256];
    snprintf(msg, sizeof(msg), "Stimulus file created: %s", filename);
    log_message(tb, msg);
    
    return 0;
}

int validate_rtl_files(testbench_t* tb) {
    log_message(tb, "Validating RTL files...");
    
    const char* rtl_files[] = {
        "rtl/CPUtop.v",
        "rtl/SIMDadd.v",
        "rtl/SIMDmultiply.v", 
        "rtl/SIMDshifter.v",
        "rtl/processor_tb.v"
    };
    
    int num_files = sizeof(rtl_files) / sizeof(rtl_files[0]);
    int found_count = 0;
    
    for (int i = 0; i < num_files; i++) {
        FILE* f = fopen(rtl_files[i], "r");
        if (f) {
            fclose(f);
            char msg[256];
            snprintf(msg, sizeof(msg), "Found RTL file: %s", rtl_files[i]);
            log_message(tb, msg);
            found_count++;
        } else {
            char msg[256];
            snprintf(msg, sizeof(msg), "WARNING: RTL file not found: %s", rtl_files[i]);
            log_message(tb, msg);
        }
    }
    
    char summary[128];
    snprintf(summary, sizeof(summary), "RTL validation: %d/%d files found", 
             found_count, num_files);
    log_message(tb, summary);
    
    return (found_count == num_files) ? 0 : 1;
}

int run_testbench(testbench_t* tb) {
    log_message(tb, "Starting testbench execution...");
    
    // Validate setup
    if (validate_rtl_files(tb) != 0) {
        log_message(tb, "WARNING: Some RTL files missing, continuing anyway...");
    }
    
    // Generate test data
    generate_test_vectors(tb);
    
    // Create files for VCS
    if (create_stimulus_files(tb) != 0) {
        log_message(tb, "ERROR: Failed to create stimulus files");
        return 1;
    }
    
    log_message(tb, "Testbench preparation completed successfully");
    log_message(tb, "Ready for VCS simulation flow");
    
    return 0;
}

void cleanup_testbench(testbench_t* tb) {
    if (tb->log_file) {
        fclose(tb->log_file);
    }
}

int main(int argc, char* argv[]) {
    const char* test_name = "processor_testbench";
    
    if (argc > 1) {
        test_name = argv[1];
    }
    
    printf("=== C Testbench: %s ===\n", test_name);
    
    testbench_t tb;
    init_testbench(&tb, test_name);
    
    int result = run_testbench(&tb);
    
    if (result == 0) {
        printf("Testbench completed successfully!\n");
    } else {
        printf("Testbench failed with error code: %d\n", result);
    }
    
    cleanup_testbench(&tb);
    return result;
}
